import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/en/": [
    {
      text: "Guide",
      icon: "lightbulb",
      prefix: "/en/guide/",
      link: "/en/guide/README.md",
      collapsible: true,
      children: [
        "what-is-justdb.md",
        "why-justdb.md",
        {
          text: "Comparison",
          icon: "balance-scale",
          prefix: "/en/guide/comparison/",
          link: "/en/guide/comparison/",
          collapsible: true,
          children: [
            "flyway.md",
            "liquibase.md",
            "sqlalchemy.md",
            "prisma.md",
            "atlas.md",
          ],
        },
        "design-philosophy.md",
        "use-cases.md",
        "ai-assisted-development.md",
        {
          text: "ORM Integration",
          icon: "code",
          prefix: "/en/guide/orm/",
          link: "/en/guide/orm/",
          collapsible: true,
          children: [
            "python.md",
            "typescript.md",
            "go.md",
          ],
        },
      ],
    },
    {
      text: "Quick Start",
      icon: "rocket",
      prefix: "/en/getting-started/",
      link: "/en/getting-started/README.md",
      collapsible: true,
      children: [
        "installation.md",
        "quick-start.md",
        "first-schema.md",
        "migration-basics.md",
        "spring-boot-integration.md",
        "common-tasks.md",
      ],
    },
    {
      text: "Cheatsheet",
      icon: "bolt",
      prefix: "/en/cheatsheet/",
      link: "/en/cheatsheet/",
      collapsible: true,
      children: [
        "serial.md",
        "virtual-column.md",
        "plugin.md",
        "type-mapping.md",
        "lifecycle-hooks.md",
        "reference-system.md",
        "migration.md",
      ],
    },
    {
      text: "Reference",
      icon: "book",
      prefix: "/en/reference/",
      collapsible: true,
      children: [
        {
          text: "Schema Definition",
          icon: "table",
          prefix: "/en/reference/schema/",
          link: "/en/reference/schema/README.md",
          collapsible: true,
          children: [
            "table.md",
            "column.md",
            "index.md",
            "constraint.md",
            "view.md",
            "sequence.md",
            "trigger.md",
            "procedure.md",
            "lifecycle-hooks.md",
          ],
        },
        {
          text: "Format Support",
          icon: "file-code",
          prefix: "/en/reference/formats/",
          link: "/en/reference/formats/README.md",
          collapsible: true,
          children: [
            "yaml.md",
            "json.md",
            "xml.md",
            "toml.md",
            "properties.md",
            "sql.md",
            "markdown.md",
            "excel.md",
          ],
        },
        {
          text: "CLI Tools",
          icon: "terminal",
          prefix: "/en/reference/cli/",
          link: "/en/reference/cli/README.md",
          collapsible: true,
          children: [
            "commands.md",
            "interactive-mode.md",
            "configuration.md",
            "file-loading.md",
          ],
        },
        {
          text: "API Reference",
          icon: "code",
          prefix: "/en/reference/api/",
          link: "/en/reference/api/README.md",
          collapsible: true,
          children: [
            "java-api.md",
            "jdbc-driver.md",
            "schema-loader.md",
            "schema-deployer.md",
            "schema-diff.md",
          ],
        },
        {
          text: "Database Support",
          icon: "database",
          prefix: "/en/reference/databases/",
          link: "/en/reference/databases/README.md",
          collapsible: true,
          children: [
            "mysql.md",
            "postgresql.md",
            "oracle.md",
            "sql-server.md",
            "h2.md",
            "sqlite.md",
            "chinese-databases.md",
          ],
        },
        {
          text: "AI Integration",
          icon: "robot",
          prefix: "/en/reference/ai/",
          link: "/en/reference/ai/README.md",
          collapsible: true,
          children: [
            "natural-language.md",
            "ai-schema-generation.md",
            "ai-migration-assistant.md",
          ],
        },
      ],
    },
    {
      text: "Design",
      icon: "pen-to-square",
      prefix: "/en/design/",
      collapsible: true,
      children: [
        {
          text: "Architecture",
          icon: "sitemap",
          prefix: "/en/design/architecture/",
          link: "/en/design/architecture/README.md",
          collapsible: true,
          children: [
            "README.md",
            "overview.md",
            "layers.md",
            "components.md",
            "core-components.md",
            "data-flow.md",
            "plugins.md",
          ],
        },
        {
          text: "Schema System",
          icon: "layer-group",
          prefix: "/en/design/schema-system/",
          link: "/en/design/schema-system/README.md",
          collapsible: true,
          children: [
            "README.md",
            "overview.md",
            "type-hierarchy.md",
            "alias-system.md",
            "schema-evolution.md",
            "reference-system.md",
            "extension-points.md",
            "extension-points-impl.md",
            "virtual-columns.md",
            "definition.md",
          ],
        },
        {
          text: "Template System",
          icon: "file-lines",
          prefix: "/en/design/template-system/",
          link: "/en/design/template-system/README.md",
          collapsible: true,
          children: [
            "README.md",
            "overview.md",
            "handlebars-templates.md",
            "inheritance.md",
            "lineage-templates.md",
            "safe-drop-templates.md",
            "custom-templates.md",
            "helpers.md",
          ],
        },
        {
          text: "Migration System",
          icon: "rotate",
          prefix: "/en/design/migration-system/",
          link: "/en/design/migration-system/README.md",
          collapsible: true,
          children: [
            "README.md",
            "overview.md",
            "diff-engine.md",
            "schema-evolution.md",
            "backup-mechanism.md",
            "history-tracking.md",
          ],
        },
        {
          text: "JDBC Driver",
          icon: "plug",
          prefix: "/en/design/jdbc-driver/",
          link: "/en/design/jdbc-driver/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "implementation.md",
            "virtual-tables.md",
            "mysql-protocol.md",
          ],
        },
        {
          text: "History Service",
          icon: "clock-rotate-left",
          prefix: "/en/design/history-service/",
          link: "/en/design/history-service/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "architecture.md",
            "hash-based-history.md",
          ],
        },
        {
          text: "Terraform Provider",
          icon: "cloud",
          prefix: "/en/design/terraform-provider/",
          link: "/en/design/terraform-provider/README.md",
          collapsible: true,
          children: [
            "README.md",
            "provider-implementation.md",
            "deployment.md",
            "cloud-api.md",
          ],
        },
        {
          text: "Convention Inference",
          icon: "wand-magic-sparkles",
          prefix: "/en/design/convention-inference/",
          link: "/en/design/convention-inference/overview.md",
          collapsible: true,
          children: [
            "overview.md",
          ],
        },
      ],
    },
    {
      text: "Development",
      icon: "wrench",
      prefix: "/en/development/",
      collapsible: true,
      children: [
        {
          text: "Build",
          icon: "hammer",
          prefix: "/en/development/build/",
          link: "/en/development/build/build-from-source.md",
          collapsible: true,
          children: [
            "build-from-source.md",
            "maven-structure.md",
            "testing.md",
          ],
        },
        {
          text: "Plugin Development",
          icon: "puzzle-piece",
          prefix: "/en/development/plugin-development/",
          link: "/en/development/plugin-development/README.md",
          collapsible: true,
          children: [
            "README.md",
            "database-adapter.md",
            "custom-templates.md",
            "extension-points.md",
            "template-helpers.md",
            "schema-formats.md",
          ],
        },
        {
          text: "Contributing",
          icon: "handshake",
          prefix: "/en/development/contributing/",
          link: "/en/development/contributing/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "coding-standards.md",
            "commit-conventions.md",
            "pull-request.md",
            "release-process.md",
          ],
        },
        {
          text: "Architecture Decisions",
          icon: "scroll",
          prefix: "/en/development/architecture-decisions/",
          link: "/en/development/architecture-decisions/adr-template.md",
          collapsible: true,
          children: [
            "adr-template.md",
            "adr-001-alias-system.md",
            "adr-002-template-engine.md",
            "adr-003-lifecycle-hooks.md",
          ],
        },
      ],
    },
    {
      text: "Roadmap & Plans",
      icon: "road",
      prefix: "/en/plans/",
      link: "/en/plans/README.md",
      collapsible: true,
      children: [
        "README.md",
        "roadmap.md",
        "current-todos.md",
        {
          text: "Historical Plans",
          icon: "history",
          prefix: "/en/plans/historical-plans/",
          collapsible: true,
          children: [
            "ai-agent-refactor.md",
            "function-implementation.md",
            "hash-history.md",
            "mcp-integration.md",
            "sql-executor-refactor.md",
            "migrate-integration.md",
          ],
        },
      ],
    },
  ],
});
