import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/": [
    {
      text: "指南",
      icon: "lightbulb",
      prefix: "/guide/",
      link: "/guide/README.md",
      collapsible: true,
      children: [
        "what-is-justdb.md",
        "why-justdb.md",
        {
          text: "与其他工具对比",
          icon: "balance-scale",
          prefix: "/guide/comparison/",
          link: "/guide/comparison/",
          collapsible: true,
          children: [
            "flyway.md",
            "liquibase.md",
            "sqlalchemy.md",
            "prisma.md",
            "atlas.md",
          ],
        },
        "design-philosophy.md",
        "use-cases.md",
      ],
    },
    {
      text: "快速开始",
      icon: "rocket",
      prefix: "/getting-started/",
      link: "/getting-started/README.md",
      collapsible: true,
      children: [
        "installation.md",
        "quick-start.md",
        "first-schema.md",
        "migration-basics.md",
        "spring-boot-integration.md",
        "common-tasks.md",
      ],
    },
    {
      text: "参考文档",
      icon: "book",
      prefix: "/reference/",
      collapsible: true,
      children: [
        {
          text: "Schema 定义",
          icon: "table",
          prefix: "/reference/schema/",
          link: "/reference/schema/README.md",
          collapsible: true,
          children: [
            "table.md",
            "column.md",
            "index.md",
            "constraint.md",
            "view.md",
            "sequence.md",
            "trigger.md",
            "procedure.md",
            "lifecycle-hooks.md",
          ],
        },
        {
          text: "格式支持",
          icon: "file-code",
          prefix: "/reference/formats/",
          link: "/reference/formats/README.md",
          collapsible: true,
          children: [
            "yaml.md",
            "json.md",
            "xml.md",
            "toml.md",
            "properties.md",
            "sql.md",
            "markdown.md",
            "excel.md",
          ],
        },
        {
          text: "CLI 工具",
          icon: "terminal",
          prefix: "/reference/cli/",
          link: "/reference/cli/README.md",
          collapsible: true,
          children: [
            "commands.md",
            "interactive-mode.md",
            "configuration.md",
            "file-loading.md",
          ],
        },
        {
          text: "API 参考",
          icon: "code",
          prefix: "/reference/api/",
          link: "/reference/api/README.md",
          collapsible: true,
          children: [
            "java-api.md",
            "jdbc-driver.md",
            "schema-loader.md",
            "schema-deployer.md",
            "schema-diff.md",
          ],
        },
        {
          text: "数据库支持",
          icon: "database",
          prefix: "/reference/databases/",
          link: "/reference/databases/README.md",
          collapsible: true,
          children: [
            "mysql.md",
            "postgresql.md",
            "oracle.md",
            "sql-server.md",
            "h2.md",
            "sqlite.md",
            "chinese-databases.md",
          ],
        },
        {
          text: "AI 集成",
          icon: "robot",
          prefix: "/reference/ai/",
          link: "/reference/ai/README.md",
          collapsible: true,
          children: [
            "natural-language.md",
            "ai-schema-generation.md",
            "ai-migration-assistant.md",
          ],
        },
      ],
    },
    {
      text: "设计文档",
      icon: "pen-to-square",
      prefix: "/design/",
      collapsible: true,
      children: [
        {
          text: "架构设计",
          icon: "sitemap",
          prefix: "/design/architecture/",
          link: "/design/architecture/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "layered-architecture.md",
            "core-components.md",
            "plugin-system.md",
            "template-engine.md",
            "data-flow.md",
          ],
        },
        {
          text: "Schema 系统",
          icon: "layer-group",
          prefix: "/design/schema-system/",
          link: "/design/schema-system/type-hierarchy.md",
          collapsible: true,
          children: [
            "type-hierarchy.md",
            "alias-system.md",
            "schema-evolution.md",
            "reference-system.md",
            "extension-points.md",
          ],
        },
        {
          text: "模板系统",
          icon: "file-lines",
          prefix: "/design/template-system/",
          link: "/design/template-system/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "handlebars-templates.md",
            "template-inheritance.md",
            "lineage-templates.md",
            "safe-drop-templates.md",
            "template-development.md",
          ],
        },
        {
          text: "迁移系统",
          icon: "rotate",
          prefix: "/design/migration-system/",
          link: "/design/migration-system/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "diff-engine.md",
            "schema-evolution.md",
            "history-tracking.md",
            "backup-mechanism.md",
          ],
        },
        {
          text: "JDBC 驱动",
          icon: "plug",
          prefix: "/design/jdbc-driver/",
          link: "/design/jdbc-driver/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "implementation.md",
            "virtual-tables.md",
            "mysql-protocol.md",
          ],
        },
        {
          text: "历史服务",
          icon: "clock-rotate-left",
          prefix: "/design/history-service/",
          link: "/design/history-service/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "architecture.md",
            "hash-based-history.md",
          ],
        },
      ],
    },
    {
      text: "开发指南",
      icon: "wrench",
      prefix: "/development/",
      collapsible: true,
      children: [
        {
          text: "构建",
          icon: "hammer",
          prefix: "/development/build/",
          link: "/development/build/build-from-source.md",
          collapsible: true,
          children: [
            "build-from-source.md",
            "maven-structure.md",
            "testing.md",
          ],
        },
        {
          text: "插件开发",
          icon: "puzzle-piece",
          prefix: "/development/plugin-development/",
          link: "/development/plugin-development/README.md",
          collapsible: true,
          children: [
            "README.md",
            "database-adapter.md",
            "custom-templates.md",
            "extension-points.md",
            "template-helpers.md",
            "schema-formats.md",
          ],
        },
        {
          text: "贡献指南",
          icon: "handshake",
          prefix: "/development/contributing/",
          link: "/development/contributing/overview.md",
          collapsible: true,
          children: [
            "overview.md",
            "coding-standards.md",
            "commit-conventions.md",
            "pull-request.md",
            "release-process.md",
          ],
        },
        {
          text: "架构决策记录",
          icon: "scroll",
          prefix: "/development/architecture-decisions/",
          link: "/development/architecture-decisions/adr-template.md",
          collapsible: true,
          children: [
            "adr-template.md",
            "adr-001-alias-system.md",
            "adr-002-template-engine.md",
            "adr-003-lifecycle-hooks.md",
          ],
        },
      ],
    },
    {
      text: "路线图与计划",
      icon: "road",
      prefix: "/plans/",
      link: "/plans/README.md",
      collapsible: true,
      children: [
        "README.md",
        "roadmap.md",
        "current-todos.md",
        {
          text: "历史计划",
          icon: "history",
          prefix: "/plans/historical-plans/",
          collapsible: true,
          children: [
            "ai-agent-refactor.md",
            "function-implementation.md",
            "hash-history.md",
            "mcp-integration.md",
            "sql-executor-refactor.md",
            "migrate-integration.md",
          ],
        },
      ],
    },
  ],
});
